# Generated by Django 3.2.20 on 2023-08-03 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20230803_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Onbording', 'Онбординг'), ('In progress', 'В работе'), ('Production', 'Проект взлетел'), ('Tests', 'Тестирование')], default='Onbording', max_length=20, verbose_name='Статус проекта')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания задачи')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления обносления задачи')),
                ('deadline', models.DateTimeField(verbose_name='Срок исполнения задачи')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название задачи')),
            ],
        ),
        migrations.CreateModel(
            name='TaskUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='task.task', verbose_name='Задача')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Задача пользователя',
                'verbose_name_plural': 'Задача пользователя',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='asigned_to',
            field=models.ManyToManyField(blank=True, to='task.TaskUser', verbose_name='Участники задачи'),
        ),
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(related_name='related_tasks', to='projects.Tag', verbose_name='Тэги'),
        ),
    ]
