# Generated by Django 3.2.20 on 2023-08-03 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0003_alter_taskuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='asigned_to',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Участники задачи'),
        ),
    ]
