# Generated by Django 3.2.20 on 2023-08-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_asigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='asigned_to',
            new_name='assigned_to',
        ),
    ]
