# Generated by Django 3.2.20 on 2023-08-12 09:26

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="project",
            name="tasks",
        ),
        migrations.RemoveField(
            model_name="task",
            name="project",
        ),
        migrations.AddField(
            model_name="project",
            name="project_tasks",
            field=models.ManyToManyField(
                blank=True, related_name="project", to="projects.Task", verbose_name="Задачи проекта"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="task_project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="projects.project",
                verbose_name="Проект",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="start",
            field=models.DateField(default=datetime.date(2023, 8, 12), verbose_name="Дата начала проекта"),
        ),
    ]
