# Generated by Django 3.2.20 on 2023-08-04 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projectuser",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_participants",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Участник",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор Проекта",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                through="projects.ProjectUser",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Участники проекта",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="projects", to="projects.Tag", verbose_name="Тэги"),
        ),
        migrations.AddField(
            model_name="project",
            name="tasks",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="projects.Task", verbose_name="Задачи проекта"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectuser",
            constraint=models.UniqueConstraint(fields=("user_id", "project_id"), name="unique_user_project"),
        ),
    ]
