# Generated by Django 3.2.20 on 2023-08-04 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task",
                to="projects.project",
                verbose_name="Проект",
            ),
            preserve_default=False,
        ),
    ]
