# Generated by Django 3.2.20 on 2023-08-03 19:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "Задача", "verbose_name_plural": "Задачи"},
        ),
    ]
