# Generated by Django 3.2.20 on 2023-08-15 13:15

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_auto_20230812_0926"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="project_tasks",
        ),
        migrations.AlterField(
            model_name="project",
            name="start",
            field=models.DateField(default=datetime.date(2023, 8, 15), verbose_name="Дата начала проекта"),
        ),
    ]
