# Generated by Django 3.2.20 on 2023-08-23 11:12

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_auto_20230815_1615"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="start",
            field=models.DateField(default=datetime.date(2023, 8, 23), verbose_name="Дата начала проекта"),
        ),
    ]
