# Generated by Django 3.2.20 on 2023-08-29 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20230815_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Project One', max_length=254, verbose_name='Название Проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start',
            field=models.DateField(default=datetime.date(2023, 8, 29), verbose_name='Дата начала проекта'),
        ),
    ]
