# Generated by Django 3.2.20 on 2023-08-04 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала проекта'),
        ),
    ]
