# Generated by Django 3.2.20 on 2023-07-18 10:51

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start', models.TimeField(verbose_name='Время начала работы')),
                ('work_finish', models.TimeField(verbose_name='Время окончания работы')),
            ],
            options={
                'verbose_name': 'График работы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='example@site.mail', max_length=254, unique=True, verbose_name='адрес электронной почты')),
                ('password', models.CharField(max_length=150, verbose_name='Пароль')),
                ('first_name', models.CharField(help_text='Иван', max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Иванов', max_length=150, verbose_name='Фамилия')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('editor', 'Редактор'), ('executor', 'Исполнитель')], help_text='Ваша должность', max_length=20, verbose_name='Должность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации пользователя')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления данных пользователя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный пользователь')),
                ('user_timezone', models.CharField(max_length=150, verbose_name='Часовой пояс пользователя')),
                ('photo', models.ImageField(upload_to='media/', verbose_name='Аватар пользователя')),
                ('telephone_number', models.SmallIntegerField(blank=True, null=True, verbose_name='Номер телефона')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('timetable', models.ManyToManyField(related_name='user_set', to='users.TimeTable', verbose_name='График работы')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
    ]
