# Generated by Django 3.2.20 on 2023-07-18 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timetable",
            options={"ordering": ["id"], "verbose_name": "График работы", "verbose_name_plural": "График работы"},
        ),
    ]
