# Generated by Django 3.2.20 on 2023-07-18 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Активный пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, help_text='Иванов', max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Аватар пользователя'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='timetable',
        ),
        migrations.AddField(
            model_name='user',
            name='timetable',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_set', to='users.timetable', verbose_name='График работы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_timezone',
            field=models.CharField(blank=True, max_length=150, verbose_name='Часовой пояс пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, verbose_name='Логин'),
        ),
    ]
