# Generated by Django 3.2.20 on 2023-08-05 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_telephone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeZone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=150)),
                ("label", models.CharField(blank=True, max_length=250)),
                ("offset", models.SmallIntegerField()),
                ("abbrev", models.CharField(blank=True, max_length=50)),
                ("altName", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "verbose_name": "Часовой пояс",
                "verbose_name_plural": "Часовые пояса",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_timezone",
        ),
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.timezone",
                verbose_name="Часовой пояс пользователя",
            ),
        ),
    ]
