# Generated by Django 3.2.20 on 2023-07-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230718_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='timetable',
        ),
        migrations.AddField(
            model_name='user',
            name='timetable',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_set', to='users.TimeTable', verbose_name='График работы'),
        ),
    ]
