# Generated by Django 3.2.20 on 2023-08-24 05:37

import django_resized.forms
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_auto_20230815_1615"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=150, verbose_name="Пароль"),
        ),
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                keep_meta=True,
                null=True,
                quality=75,
                scale=1,
                size=[400, 400],
                upload_to="media/",
                validators=[users.models.User.validate_photo],
                verbose_name="Аватар пользователя",
            ),
        ),
    ]
