# Generated by Django 3.2.20 on 2023-08-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_auto_20230824_0537"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(blank=True, help_text="Ваша должность", max_length=50, verbose_name="Должность"),
        ),
    ]
