# Generated by Django 3.2.20 on 2023-08-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="work_finish",
            field=models.TimeField(blank=True, null=True, verbose_name="Время окончания работы"),
        ),
        migrations.AlterField(
            model_name="user",
            name="work_start",
            field=models.TimeField(blank=True, null=True, verbose_name="Время начала работы"),
        ),
    ]
